[application]

[web.app]
# base_path = "dioxus-plumb"

# HTML title tag content
title = "Drawn Systems in Dioxus"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
